package com.example.ui

enum class AppLanguage(val displayName: String, val nativeName: String, val code: String) {
    ENGLISH("English", "English", "en"),
    GUJARATI("Gujarati", "ગુજરાતી", "gu"),
    MARATHI("Marathi", "मराठी", "mr"),
    ODIA("Odia", "ଓଡ଼ିଆ", "or")
}

object Localization {
    private val translations = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_title" to "AMIHA ICS manager",
            "field_officer_mode" to "Online • Field Officer Mode",
            "inspector_mode" to "Online • Inspector Mode",
            "sync_status" to "Sync Status",
            "pending_syncs" to "Pending Syncs",
            "total_farmers" to "Total Farmers",
            "certified_farmers" to "Certified",
            "under_inspection" to "Under Inspection",
            "search_farmer_placeholder" to "Search Farmer ID or Name...",
            "recent_activities" to "Recent Farmers",
            "last_synced" to "Last synced",
            "sync_all" to "Sync All",
            "view_all" to "View All",
            "add_farmer" to "Add Farmer",
            "farmers_count" to "Farmers Registered",
            "village" to "Village",
            "crops" to "Crops",
            "farming_method" to "Farming Method",
            "certification_status" to "Certification Status",
            "compliance_summary" to "Compliance Summary",
            "unregistered" to "Unregistered",
            "suspended" to "Suspended",
            "registered" to "Registered",
            "certified" to "Certified",
            "status" to "Status",
            "login_title" to "AMIHA ICS MANAGER",
            "login_subtitle" to "Internal Control System compliance in the field",
            "staff_auth" to "Staff Authentication",
            "username_label" to "Email OR Username",
            "password_label" to "Password",
            "demo_profile_prompt" to "Choose a demo profile to login:",
            "sign_in_btn" to "SIGN IN",
            "new_farmer_reg" to "New Farmer Registration",
            "edit_farmer_rec" to "Edit Farmer Record",
            "save_farmer_btn" to "Save Farmer Record",
            "personal_info" to "Personal Information",
            "full_name_label" to "Full Name",
            "mobile_label" to "Primary Phone / Mobile",
            "dob_label" to "Date of Birth",
            "ics_group_label" to "ICS Group / Cluster",
            "geographic_info" to "Geographical Location",
            "village_label" to "Village Name",
            "gps_coords_label" to "GPS Coordinates (Lat, Long)",
            "grab_gps_btn" to "Auto Grab",
            "household_members_sec" to "Household Members Details",
            "member_name" to "Member Name",
            "relationship" to "Relationship",
            "age" to "Age",
            "add_member_btn" to "Add Member",
            "farm_plots_sec" to "Farm Plots Details",
            "plot_id" to "Plot ID",
            "total_acres" to "Total Acres / Size",
            "primary_crops" to "Primary Crops (comma separated)",
            "secondary_crops" to "Secondary Crops (comma separated)",
            "add_plot_btn" to "Add Plot",
            "livestock_sec" to "Livestock Details",
            "animal_type" to "Animal Type (e.g. Cow, Buffalo)",
            "animal_count" to "Count",
            "add_livestock_btn" to "Add Livestock",
            "log_farm_inspection" to "Log Farm Inspection",
            "inspect_btn" to "Inspect",
            "soil_health_q" to "Soil Health Assessment (No erosion, rich organic matter?)",
            "organic_fert_q" to "Organic Fertilizer Use Check (Composting, green manures used?)",
            "chemical_fert_q" to "Chemical Fertilizer/Pesticide Check (Zero synthetic chemicals?)",
            "save_inspection_btn" to "Save Inspection Report",
            "pass" to "PASS",
            "fail" to "FAIL",
            "yes" to "YES",
            "no" to "NO",
            "farmer_details" to "Farmer Details",
            "compliance_inspections" to "Compliance Inspections",
            "no_inspections" to "No historical inspections carried out yet.",
            "audited_by" to "Audited by",
            "date" to "Date",
            "soil_health" to "Soil Health",
            "organic_manure" to "Organic Manure",
            "no_chemical" to "No Synthetic Chemical",
            "compliance_status" to "Compliance Status",
            "switch_lang" to "Language / ભાષા / भाषा / ଭାଷା",
            "logout" to "Logout",
            "personal_contact_tab" to "Personal & Contact",
            "village_gps_tab" to "Village & GPS",
            "household_info_tab" to "Household Info",
            "plots_tab" to "Plots",
            "crops_animals_tab" to "Crops & Animals",
            "organic" to "Organic",
            "transitional" to "In Transition",
            "conventional" to "Conventional",
            "pending" to "Pending",
            "conduct_inspection" to "Conduct Inspection",
            "audit_target_farmer" to "AUDIT TARGET FARMER",
            "select_audit_result" to "Select Audit Result *",
            "submit_compliance_report" to "SUBMIT COMPLIANCE REPORT",
            "auditor_name" to "Auditor Name",
            "audit_date" to "Audit Date",
            "critical_compliance_notice" to "CRITICAL COMPLIANCE NOTICE",
            "fail_notice_text" to "Declaring FAIL will suspend the certification status. You are REQUIRED to document any crop/pesticide non-conformance observations or violations of organic regulations in full details below.",
            "obs_notes_fail" to "Non-Conformance Observations (Required) *",
            "obs_notes_optional" to "Inspection Observations / Audit Logs (Optional)",
            "full_complies" to "Complies fully",
            "red_flags" to "Red Flags / Alert",
            "need_verification" to "Need verification",
            "registration_id" to "Registration ID",
            "crops_farming_practices" to "Crops & Farming Practices",
            "livestock_asset_details" to "Livestock & Animal Asset Details",
            "ics_group_compliance_record" to "Internal Control System Group & Compliance Record",
            "certification_file" to "Certification File",
            "ics_group_name" to "ICS Group Name",
            "reg_mapped_date" to "Registration Mapped Date",
            "last_active_inspection" to "Last Active Inspection",
            "inspection_result_status" to "Inspection Result Status",
            "next_scheduled_audit" to "Next Scheduled Audit",
            "red_flags_log" to "Non-Conformance Red-Flags log:",
            "unscheduled" to "Unscheduled",
            "never_inspected" to "Never Inspected",
            "pending_inspection" to "Pending Inspection",
            "primary_profile_identity" to "Primary Profile & Identity",
            "village_location" to "Village Location",
            "gram_panchayat" to "Gram Panchayat",
            "taluka" to "Taluka",
            "district" to "District",
            "state" to "State",
            "geographic_gps" to "Geographical GPS",
            "primary_crops_mapped" to "Primary Crops Mapped",
            "intercrops_secondary" to "Intercrops / Secondary Crops",
            "seeds_sourcing" to "Seeds Sourcing",
            "previous_yield" to "Previous Yield",
            "is_chem_pesticides_used" to "Is Chem Pesticides Used?",
            "is_chem_fertilizers_used" to "Is Chem Fertilizers Used?",
            "pesticide_log" to "Pesticide Log",
            "fertilizer_log" to "Fertilizer Log",
            "no_yield_logs" to "No Yield Logs",
            "none_listed" to "None listed",
            "un_saved_warning" to "This record has un-saved local modifications. It will sync automatically when online, or can be synchronised manually in App Settings.",
            "previous" to "Previous",
            "next_sec" to "Next Section",
            "complete_sync" to "Complete & Sync",
            "edit_farmer_rec" to "Edit Farmer Record",
            "new_farmer_reg" to "New Farmer Registration",
            "log_farm_inspection" to "Log Farm Inspection"
        ),
        AppLanguage.GUJARATI to mapOf(
            "app_title" to "આઈસીએસ મેનેજર",
            "field_officer_mode" to "ઓનલાઇન • ફિલ્ડ ઓફિસર મોડ",
            "inspector_mode" to "ઓનલાઇન • ઇન્સ્પેક્ટર મોડ",
            "sync_status" to "સિંક સ્થિતિ",
            "pending_syncs" to "બાકી સિંક",
            "total_farmers" to "કુલ ખેડૂતો",
            "certified_farmers" to "પ્રમાણિત",
            "under_inspection" to "તપાસ હેઠળ",
            "search_farmer_placeholder" to "ખેડૂત ID અથવા નામ શોધો...",
            "recent_activities" to "તાજેતરના ખેડૂતો",
            "last_synced" to "છેલ્લે સિંક કર્યું",
            "sync_all" to "બધા સિંક કરો",
            "view_all" to "બધા જુઓ",
            "add_farmer" to "ખેડૂત ઉમેરો",
            "farmers_count" to "નોંધાયેલા ખેડૂતો",
            "village" to "ગામ",
            "crops" to "પાક",
            "farming_method" to "ખેતી પદ્ધતિ",
            "certification_status" to "પ્રમાણપત્ર સ્થિતિ",
            "compliance_summary" to "પાલન સારાંશ",
            "unregistered" to "અનોંધાયેલ",
            "suspended" to "સ્થગિત",
            "registered" to "નોંધાયેલ",
            "certified" to "પ્રમાણિત",
            "status" to "સ્થિતિ",
            "login_title" to "આઈસીએસ મેનેજર",
            "login_subtitle" to "ક્ષેત્રમાં આંતરિક નિયંત્રણ સિસ્ટમનું પાલન",
            "staff_auth" to "સ્ટાફ પ્રમાણન",
            "username_label" to "ઈમેલ અથવા વપરાશકર્તા નામ",
            "password_label" to "પાસવર્ડ",
            "demo_profile_prompt" to "લોગિન કરવા માટે ડેમો પ્રોફાઇલ પસંદ કરો:",
            "sign_in_btn" to "લોગ ઇન કરો",
            "new_farmer_reg" to "નવી ખેડૂત નોંધણી",
            "edit_farmer_rec" to "ખેડૂતનો રેકોર્ડ સુધારો",
            "save_farmer_btn" to "ખેડૂત રેકોર્ડ સાચવો",
            "personal_info" to "વ્યક્તિગત માહિતી",
            "full_name_label" to "પૂરું નામ",
            "mobile_label" to "પ્રાથમિક ફોન / મોબાઈલ",
            "dob_label" to "જન્મ તારીખ",
            "ics_group_label" to "આઈસીએસ ગ્રુપ / ક્લસ્ટર",
            "geographic_info" to "ભૌગોલિક સ્થાન",
            "village_label" to "ગામનું નામ",
            "gps_coords_label" to "જીપીએસ કોઓર્ડિનેટ્સ (અક્ષાંશ, રેખાંશ)",
            "grab_gps_btn" to "ઓટો ગ્રેબ",
            "household_members_sec" to "ઘરના સભ્યોની વિગતો",
            "member_name" to "સભ્યનું નામ",
            "relationship" to "સંબંધ",
            "age" to "ઉંમર",
            "add_member_btn" to "સભ્ય ઉમેરો",
            "farm_plots_sec" to "ખેતરના પ્લોટની વિગતો",
            "plot_id" to "પ્લોટ ID",
            "total_acres" to "કુલ એકર / કદ",
            "primary_crops" to "મુખ્ય પાક (અલ્પવિરામથી અલગ કરો)",
            "secondary_crops" to "ગૌણ પાક (અલ્પવિરામથી અલગ કરો)",
            "add_plot_btn" to "પ્લોટ ઉમેરો",
            "livestock_sec" to "પશુધનની વિગતો",
            "animal_type" to "પશુ પ્રકાર (દા.ત. ગાય, ભેંસ)",
            "animal_count" to "સંખ્યા",
            "add_livestock_btn" to "પશુધન ઉમેરો",
            "log_farm_inspection" to "ફાર્મ નિરીક્ષણ રેકોર્ડ કરો",
            "inspect_btn" to "નિરીક્ષણ કરો",
            "soil_health_q" to "જમીન સ્વાસ્થ્ય આકારણી (જમીન ધોવાણ નથી, સેન્દ્રીય પદાર્થોથી સમૃદ્ધ છે?)",
            "organic_fert_q" to "સેન્દ્રીય ખાતરના ઉપયોગની તપાસ (કમ્પોસ્ટ, લીલો પડવાસ વપરાય છે?)",
            "chemical_fert_q" to "રાસાયણિક ખાતર/જંતુનાશક તપાસ (ઝીરો કૃત્રિમ રસાયણો?)",
            "save_inspection_btn" to "નિરીક્ષણ અહેવાલ સાચવો",
            "pass" to "પાસ (સફળ)",
            "fail" to "નાપાસ (નિષ્ફળ)",
            "yes" to "હા",
            "no" to "ના",
            "farmer_details" to "ખેડૂતની વિગતો",
            "compliance_inspections" to "પાલન નિરીક્ષણ ઇતિહાસ",
            "no_inspections" to "હજુ સુધી કોઈ નિરીક્ષણ કરવામાં આવ્યા નથી.",
            "audited_by" to "નિરીક્ષક",
            "date" to "તારીખ",
            "soil_health" to "જમીન સ્વાસ્થ્ય",
            "organic_manure" to "સેન્દ્રીય ખાતર",
            "no_chemical" to "કોઈ કૃત્રિમ રસાયણ નથી",
            "compliance_status" to "પાલન સ્થિતિ",
            "switch_lang" to "ભાષા બદલો",
            "logout" to "લોગ આઉટ",
            "personal_contact_tab" to "વ્યક્તિગત અને સંપર્ક",
            "village_gps_tab" to "ગામ અને જીપીએસ",
            "household_info_tab" to "ઘરની વિગતો",
            "plots_tab" to "પ્લોટ",
            "crops_animals_tab" to "પાક અને પ્રાણીઓ",
            "organic" to "સેન્દ્રીય (ઓર્ગેનિક)",
            "transitional" to "બદલાવ હેઠળ",
            "conventional" to "પરંપરાગત",
            "pending" to "બાકી છે",
            "conduct_inspection" to "નિરીક્ષણ શરૂ કરો",
            "audit_target_farmer" to "લક્ષ્ય ખેડૂતનું નિરીક્ષણ",
            "select_audit_result" to "નિરીક્ષણ પરિણામ પસંદ કરો *",
            "submit_compliance_report" to "પાલન અહેવાલ સબમિટ કરો",
            "auditor_name" to "નિરીક્ષકનું નામ",
            "audit_date" to "નિરીક્ષણ તારીખ",
            "critical_compliance_notice" to "જટીલ પાલન સૂચના",
            "fail_notice_text" to "નાપાસ (FAIL) જાહેર કરવાથી પ્રમાણપત્રની સ્થિતિ સ્થગિત થઈ જશે. તમારે કોઈપણ પાક/જંતુનાશક બિન-પાલન અવલોકનો અથવા કાર્બનિક નિયમોના ઉલ્લંઘનને નીચે સંપૂર્ણ વિગતોમાં દસ્તાવેજીકૃત કરવું જરૂરી છે.",
            "obs_notes_fail" to "બિન-પાલન અવલોકનો (જરૂરી) *",
            "obs_notes_optional" to "નિરીક્ષણ અવલોકનો / ઓડિટ વિગતો (વૈકલ્પિક)",
            "full_complies" to "સંપૂર્ણ પાલન કરે છે",
            "red_flags" to "લાલ ઝંડી / ચેતવણી",
            "need_verification" to "ચકાસણીની જરૂર છે",
            "registration_id" to "નોંધણી આઈડી",
            "crops_farming_practices" to "પાક અને ખેતી પદ્ધતિઓ",
            "livestock_asset_details" to "પશુધન અને પ્રાણીઓની વિગતો",
            "ics_group_compliance_record" to "આંતરિક નિયંત્રણ સિસ્ટમ જૂથ અને પાલન રેકોર્ડ",
            "certification_file" to "પ્રમાણપત્ર ફાઇલ",
            "ics_group_name" to "આઈસીએસ જૂથનું નામ",
            "reg_mapped_date" to "નોંધણી નકશા તારીખ",
            "last_active_inspection" to "છેલ્લું સક્રિય નિરીક્ષણ",
            "inspection_result_status" to "નિરીક્ષણ પરિણામ સ્થિતિ",
            "next_scheduled_audit" to "આગામી સુનિશ્ચિત ઓડિટ",
            "red_flags_log" to "બિન-પાલન લાલ ઝંડી લોગ:",
            "unscheduled" to "અનિર્ધારિત",
            "never_inspected" to "ક્યારેય નિરીક્ષણ નથી થયું",
            "pending_inspection" to "બાકી નિરીક્ષણ",
            "primary_profile_identity" to "પ્રાથમિક પ્રોફાઇલ અને ઓળખ",
            "village_location" to "ગામનું સ્થાન",
            "gram_panchayat" to "ગ્રામ પંચાયત",
            "taluka" to "તાલુકો",
            "district" to "જિલ્લો",
            "state" to "રાજ્ય",
            "geographic_gps" to "ભૌગોલિક જીપીએસ",
            "primary_crops_mapped" to "નકશા પર દર્શાવેલ મુખ્ય પાકો",
            "intercrops_secondary" to "આંતરપાક / ગૌણ પાકો",
            "seeds_sourcing" to "બિયારણ મેળવવું",
            "previous_yield" to "પાછલી ઉપજ",
            "is_chem_pesticides_used" to "શું રાસાયણિક જંતુનાશકો વપરાય છે?",
            "is_chem_fertilizers_used" to "શું રાસાયણિક ખાતરો વપરાય છે?",
            "pesticide_log" to "જંતુનાશક લોગ",
            "fertilizer_log" to "ખાતર લોગ",
            "no_yield_logs" to "ઉપજનો કોઈ લોગ નથી",
            "none_listed" to "કોઈ યાદી નથી",
            "un_saved_warning" to "આ રેકોર્ડમાં સેવ ન કરેલા સ્થાનિક ફેરહારો છે. જ્યારે ઓનલાઇન થશે ત્યારે તે આપમેળે સિંક થઈ જશે, અથવા એપ્લિકેશન સેટિંગ્સમાં મેન્યુઅલી સિંક થઈ શકે છે.",
            "previous" to "પાછળ",
            "next_sec" to "આગળનો વિભાગ",
            "complete_sync" to "પૂર્ણ કરો અને સિંક કરો",
            "edit_farmer_rec" to "ખેડૂત રેકોર્ડ સંપાદિત કરો",
            "new_farmer_reg" to "નવી ખેડૂત નોંધણી",
            "log_farm_inspection" to "ફાર્મ નિરીક્ષણ લોગ કરો"
        ),
        AppLanguage.MARATHI to mapOf(
            "app_title" to "आयसीएस व्यवस्थापक",
            "field_officer_mode" to "ऑनलाइन • क्षेत्र अधिकारी मोड",
            "inspector_mode" to "オンライン • निरीक्षक मोड",
            "sync_status" to "समक्रमण स्थिती",
            "pending_syncs" to "प्रलंबित सद्रश्य",
            "total_farmers" to "एकूण शेतकरी",
            "certified_farmers" to "प्रमाणित",
            "under_inspection" to "तपासणी सुरू",
            "search_farmer_placeholder" to "शेतकरी आयडी किंवा नाव शोधा...",
            "recent_activities" to "अलीकडील शेतकरी",
            "last_synced" to "शेवटचे समक्रमण",
            "sync_all" to "सर्व समक्रमित करा",
            "view_all" to "सर्व पहा",
            "add_farmer" to "शेतकरी जोडा",
            "farmers_count" to "नोंदणीकृत शेतकरी",
            "village" to "गाव",
            "crops" to "पिके",
            "farming_method" to "शेती पद्धत",
            "certification_status" to "प्रमाणन स्थिती",
            "compliance_summary" to "अनुपालन सारांश",
            "unregistered" to "अनोंदणीकृत",
            "suspended" to "निलंबित",
            "registered" to "नोंदणीकृत",
            "certified" to "प्रमाणित",
            "status" to "स्थिती",
            "login_title" to "आयसीएस व्यवस्थापक",
            "login_subtitle" to "क्षेत्रातील अंतर्गत नियंत्रण प्रणालीचे अनुपालन",
            "staff_auth" to "कर्मचारी प्रमाणीकरण",
            "username_label" to "ईमेल किंवा वापरकर्तानाव",
            "password_label" to "पासवर्ड",
            "demo_profile_prompt" to "लॉगिन करण्यासाठी डेमो प्रोफाइल निवडा:",
            "sign_in_btn" to "लॉगिन करा",
            "new_farmer_reg" to "नवीन शेतकरी नोंदणी",
            "edit_farmer_rec" to "शेतकरी नोंद सुधारा",
            "save_farmer_btn" to "शेतकरी नोंद जतन करा",
            "personal_info" to "वैयक्तिक माहिती",
            "full_name_label" to "पूर्ण नाव",
            "mobile_label" to "प्राथमिक फोन / मोबाईल",
            "dob_label" to "जन्मतारीख",
            "ics_group_label" to "आयसीएस गट / क्लस्टर",
            "geographic_info" to "भौगोलिक स्थान",
            "village_label" to "गावाचे नाव",
            "gps_coords_label" to "जीपीएस समन्वय (अक्षांश, रेखांश)",
            "grab_gps_btn" to "ऑटो ग्रॅब",
            "household_members_sec" to "घरातील सदस्यांचा तपशील",
            "member_name" to "सदस्याचे नाव",
            "relationship" to "नाते",
            "age" to "वय",
            "add_member_btn" to "सदस्य जोडा",
            "farm_plots_sec" to "शेतातील प्लॉटचा तपशील",
            "plot_id" to "प्लॉट आयडी",
            "total_acres" to "एकूण एकर / आकार",
            "primary_crops" to "मुख्य पिके (स्वल्पविरामाने वेगळे करा)",
            "secondary_crops" to "दुय्यम पिके (स्वल्पविरामाने वेगळे करा)",
            "add_plot_btn" to "प्लॉट जोडा",
            "livestock_sec" to "पशुधनाचा तपशील",
            "animal_type" to "प्राण्याचा प्रकार (उदा. गाय, म्हैस)",
            "animal_count" to "संख्या",
            "add_livestock_btn" to "पशुधन जोडा",
            "log_farm_inspection" to "शेत पाहणीची नोंद करा",
            "inspect_btn" to "तपासणी करा",
            "soil_health_q" to "माती आरोग्य मूल्यांकन (मातीची धूप नाही, सेंद्रिय घटक भरपूर आहेत का?)",
            "organic_fert_q" to "सेंद्रिय खतांच्या वापराची तपासणी (कंपोस्ट, हिरवळीचे खत वापरले जाते का?)",
            "chemical_fert_q" to "रासायनिक खत/कीटकनाशक तपासणी (शून्य कृत्रिम रसायने का?)",
            "save_inspection_btn" to "तपासणी अहवाल जतन करा",
            "pass" to "उत्तीर्ण (पास)",
            "fail" to "अनुत्तीर्ण (फेली)",
            "yes" to "होय",
            "no" to "नाही",
            "farmer_details" to "शेतकरी तपशील",
            "compliance_inspections" to "अनुपालन तपासणी इतिहास",
            "no_inspections" to "अद्याप कोणतीही तपासणी केली गेली नाही.",
            "audited_by" to "निरीक्षक",
            "date" to "तारीख",
            "soil_health" to "मातीचे आरोग्य",
            "organic_manure" to "सेंद्रिय खत",
            "no_chemical" to "कृत्रिम रसायने नाही",
            "compliance_status" to "अनुपालन स्थिती",
            "switch_lang" to "भाषा बदला",
            "logout" to "बाहेर पडा",
            "personal_contact_tab" to "वैयक्तिक आणि संपर्क",
            "village_gps_tab" to "गाव आणि जीपीएस",
            "household_info_tab" to "घराची माहिती",
            "plots_tab" to "प्लॉट",
            "crops_animals_tab" to "पिके आणि प्राणी",
            "organic" to "सेंद्रिय",
            "transitional" to "बदलाच्या टप्प्यात",
            "conventional" to "पारंपारिक",
            "pending" to "प्रलंबित",
            "conduct_inspection" to "तपासणी सुरू करा",
            "audit_target_farmer" to "लक्ष्य शेतकरी तपासणी",
            "select_audit_result" to "तपासणी निकाल निवडा *",
            "submit_compliance_report" to "अनुपालन अहवाल सबमिट करा",
            "auditor_name" to "निरीक्षकाचे नाव",
            "audit_date" to "तपासणी तारीख",
            "critical_compliance_notice" to "महत्त्वाची अनुपालन सूचना",
            "fail_notice_text" to "नापास (FAIL) घोषित केल्यास प्रमाणन स्थिती निलंबित होईल. खालील सविस्तर भागात पीक/कीटकनाशक गैर-अनुपालन निरीक्षणे किंवा सेंद्रिय नियमांचे उल्लंघन नोंदवणे आवश्यक आहे.",
            "obs_notes_fail" to "गैर-अनुपालन निरीक्षणे (आवश्यक) *",
            "obs_notes_optional" to "तपासणी निरीक्षणे / ऑडिट नोंदी (पर्यायी)",
            "full_complies" to "पूर्ण पूर्तता करते",
            "red_flags" to "धोक्याची घंटा / चेतावणी",
            "need_verification" to "पडताळणी आवश्यक",
            "registration_id" to "नोंदणी आयडी",
            "crops_farming_practices" to "पिके आणि शेती पद्धती",
            "livestock_asset_details" to "पशुधन आणि प्राणी मालमत्ता तपशील",
            "ics_group_compliance_record" to "अंतर्गत नियंत्रण प्रणाली गट आणि अनुपालन रेकॉर्ड",
            "certification_file" to "प्रमाणन फाइल",
            "ics_group_name" to "आयसीएस गटाचे नाव",
            "reg_mapped_date" to "नोंदणी मॅप केलेली तारीख",
            "last_active_inspection" to "शेवटची सक्रिय तपासणी",
            "inspection_result_status" to "तपासणी निकाल स्थिती",
            "next_scheduled_audit" to "पुढील अनुसूचित ऑडिट",
            "red_flags_log" to "गैर-अनुपालन रेड-फ्लॅग नोंद:",
            "unscheduled" to "नियोजित नाही",
            "never_inspected" to "कधीही तपासणी झाली नाही",
            "pending_inspection" to "तपासणी प्रलंबित",
            "primary_profile_identity" to "प्राथमिक प्रोफाइल आणि ओळख",
            "village_location" to "गावाचे स्थान",
            "gram_panchayat" to "ग्रामपंचायत",
            "taluka" to "तालुका",
            "district" to "जिल्हा",
            "state" to "राज्य",
            "geographic_gps" to "भौगोलिक जीपीएस",
            "primary_crops_mapped" to "मॅप केलेली मुख्य पिके",
            "intercrops_secondary" to "आंतरपिके / दुय्यम पिके",
            "seeds_sourcing" to "बियाणे मिळवणे",
            "previous_yield" to "मागील उत्पादन",
            "is_chem_pesticides_used" to "रासायनिक कीटकनाशके वापरली जातात का?",
            "is_chem_fertilizers_used" to "रासायनिक खते वापरली जातात का?",
            "pesticide_log" to "कीटकनाशक नोंद",
            "fertilizer_log" to "खत नोंद",
            "no_yield_logs" to "उत्पादन नोंद नाही",
            "none_listed" to "काहीही नोंद नाही",
            "un_saved_warning" to "या नोंदमध्ये जतन न केलेले स्थानिक बदल आहेत. ऑनलाइन झाल्यावर ते स्वयंचलितपणे समक्रमित होईल किंवा ॲप सेटिंग्जमध्ये मॅन्युअली समक्रमित केले जाऊ शकते.",
            "previous" to "मागे",
            "next_sec" to "पुढील विभाग",
            "complete_sync" to "पूर्ण करा आणि समक्रमित करा",
            "edit_farmer_rec" to "शेतकरी रेकॉर्ड संपादित करा",
            "new_farmer_reg" to "नवीन शेतकरी नोंदणी",
            "log_farm_inspection" to "शेत तपासणी नोंदवा"
        ),
        AppLanguage.ODIA to mapOf(
            "app_title" to "ଆଇସିଏସ ମ୍ୟାନେଜର",
            "field_officer_mode" to "ଅନଲାଇନ୍ • ଫିଲ୍ଡ ଅଫିସର ମୋଡ୍",
            "inspector_mode" to "ଅନଲାଇନ୍ • ଇନ୍ସପେକ୍ଟର ମୋଡ୍",
            "sync_status" to "ସିଙ୍କ୍ ସ୍ଥିତି",
            "pending_syncs" to "ବାକି ସିଙ୍କ୍",
            "total_farmers" to "ମୋଟ କୃଷକ",
            "certified_farmers" to "ପ୍ରମାଣିତ",
            "under_inspection" to "ଯาଞ୍ଚ ଚାଲିଛି",
            "search_farmer_placeholder" to "କୃଷକ ID କିମ୍ବା ନାମ ଖୋଜନ୍ତୁ...",
            "recent_activities" to "ସାମ୍ପ୍ରତିକ କୃଷକ",
            "last_synced" to "ଶେଷ ସିଙ୍କ୍",
            "sync_all" to "ସବୁ ସିଙ୍କ୍ କରନ୍ତୁ",
            "view_all" to "ସବୁ ଦେଖନ୍ତୁ",
            "add_farmer" to "କୃଷକ ଯୋଡନ୍ତୁ",
            "farmers_count" to "ପଞ୍ଜୀକୃତ କୃଷକ",
            "village" to "ଗ୍ରାମ",
            "crops" to "ଫସଲ",
            "farming_method" to "ଚାଷ ପ୍ରଣାଳୀ",
            "certification_status" to "ପ୍ରମାଣପତ୍ର ସ୍ଥିତି",
            "compliance_summary" to "ନିୟମ ପାଳନ ସାରାଂଶ",
            "unregistered" to "ଅପଞ୍ଜୀକୃତ",
            "suspended" to "ସ୍ଥଗିତ",
            "registered" to "ପଞ୍ଜୀକୃତ",
            "certified" to "ପ୍ରମାଣିତ",
            "status" to "ସ୍ଥିତି",
            "login_title" to "ଆଇସିଏସ ମ୍ୟାନେଜର",
            "login_subtitle" to "କ୍ଷେତ୍ରରେ ଆଭ୍ୟନ୍ତରୀଣ ନିୟନ୍ତ୍ରଣ ବ୍ୟବସ୍ଥାର ଅନୁପାଳନ",
            "staff_auth" to "କର୍ମଚାରୀ ପ୍ରମାଣୀକରଣ",
            "username_label" to "ଇମେଲ୍ କିମ୍ବା ୟୁଜର୍ ନାମ",
            "password_label" to "ପାସୱାର୍ଡ",
            "demo_profile_prompt" to "ଲଗଇନ୍ ପାଇଁ ଏକ ଡେମୋ ପ୍ରୋଫାଇଲ୍ ବାଛନ୍ତୁ:",
            "sign_in_btn" to "ଲଗଇନ୍ କରନ୍ତୁ",
            "new_farmer_reg" to "ନୂତନ କୃଷକ ପଞ୍ଜୀକରଣ",
            "edit_farmer_rec" to "କୃଷକ ତଥ୍ୟ ସଂଶୋଧନ",
            "save_farmer_btn" to "କୃଷକ ତଥ୍ୟ ସଂରକ୍ଷଣ କରନ୍ତୁ",
            "personal_info" to "ବ୍ୟକ୍ତିଗତ ସୂଚନା",
            "full_name_label" to "ପୂରା ନାମ",
            "mobile_label" to "ପ୍ରାଥମିକ ଫୋନ୍ / ମୋବାଇଲ୍",
            "dob_label" to "ଜନ୍ମ ତାରିଖ",
            "ics_group_label" to "ଆଇସିଏସ ଗ୍ରୁପ୍ / କ୍ଲଷ୍ଟର",
            "geographic_info" to "ଭୌଗୋଳିକ ସ୍ଥିତି",
            "village_label" to "ଗ୍ରାମର ନାମ",
            "gps_coords_label" to "ଜିପିଏସ କୋଅର୍ଡିନେଟ୍ସ (ଅକ୍ଷାଂଶ, ଦ୍ରାଘିମା)",
            "grab_gps_btn" to "ଅଟୋ ଗ୍ରାବ୍",
            "household_members_sec" to "ପରିବାର ସଦସ୍ୟ ବିବରଣୀ",
            "member_name" to "ସଦସ୍ୟଙ୍କ ନାମ",
            "relationship" to "ସମ୍ପର୍କ",
            "age" to "ବୟସ",
            "add_member_btn" to "ସଦସ୍ୟ ଯୋଡନ୍ତୁ",
            "farm_plots_sec" to "ଜମି ପ୍ଲଟ୍ ବିବରଣୀ",
            "plot_id" to "ପ୍ଲଟ୍ ID",
            "total_acres" to "ମୋଟ ଏକର / ଆକାର",
            "primary_crops" to "ପ୍ରାଥମିକ ଫସଲ (କମା ଦ୍ୱାରା ଅଲଗା କରନ୍ତୁ)",
            "secondary_crops" to "ଦ୍ୱିତୀୟକ ଫସଲ (କମା ଦ୍ୱାରା ଅଲଗା କରନ୍ତୁ)",
            "add_plot_btn" to "ପ୍ଲଟ୍ ଯୋଡନ୍ତୁ",
            "livestock_sec" to "ପଶୁସମ୍ପଦ ବିବରଣୀ",
            "animal_type" to "ପଶୁ ପ୍ରକାର (ଯେପରିକି ଗାଈ, ମଇଁଷି)",
            "animal_count" to "ସଂଖ୍ୟା",
            "add_livestock_btn" to "ପଶୁସମ୍ପଦ ଯୋଡନ୍ତୁ",
            "log_farm_inspection" to "ଜମି ଯାଞ୍ଚ ଲଗ୍ ପ୍ରସ୍ତୁତ",
            "inspect_btn" to "ଯାଞ୍ଚ କରନ୍ତୁ",
            "soil_health_q" to "ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟ ମୂଲ୍ୟାଙ୍କନ (ଭୂକ୍ଷୟ ନାହିଁ, ଜୈବିକ ଉପାଦାନରେ ସମୃଦ୍ଧ କି?)",
            "organic_fert_q" to "ଜୈବିକ ଖତ ବ୍ୟବହାର ଯାଞ୍ଚ (କମ୍ପୋଷ୍ଟ, ସବୁଜ ସାର ବ୍ୟବହୃତ କି?)",
            "chemical_fert_q" to "ରାସାୟନିକ ସାର/କୀଟନାଶକ ଯାଞ୍ଚ (ଶୂନ୍ୟ କୃତ୍ରିମ ସାର କି?)",
            "save_inspection_btn" to "ଯାଞ୍ଚ ରିପୋର୍ଟ ସଂରକ୍ଷଣ",
            "pass" to "ପାସ୍ (ସଫଳ)",
            "fail" to "ଫେଲ୍ (ଅସଫଳ)",
            "yes" to "ହଁ",
            "no" to "ନା",
            "farmer_details" to "କୃଷକ ବିବରଣୀ",
            "compliance_inspections" to "ନିୟମ ଅନୁପାଳନ ଯାଞ୍ଚ ଇତିହାସ",
            "no_inspections" to "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଯାଞ୍ଚ କରାଯାଇ ନାହିଁ।",
            "audited_by" to "ଯାଞ୍ଚକାରୀ",
            "date" to "ତାରିଖ",
            "soil_health" to "ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟ",
            "organic_manure" to "ଜୈବିକ ସାର",
            "no_chemical" to "କୌଣସି କୃତ୍ରିମ ସାର ନାହିଁ",
            "compliance_status" to "ନିୟମ ଅନୁପାଳନ ସ୍ଥିତି",
            "switch_lang" to "ଭାଷା ପରିବର୍ତ୍ତନ",
            "logout" to "ଲଗ୍ ଆଉଟ୍",
            "personal_contact_tab" to "ବ୍ୟକ୍ତିଗତ ଏବଂ ଯୋଗାଯୋଗ",
            "village_gps_tab" to "ଗ୍ରାମ ଏବଂ ଜିପିଏସ",
            "household_info_tab" to "ପରିବାର ବିବରଣୀ",
            "plots_tab" to "ପ୍ଲଟ୍",
            "crops_animals_tab" to "ଫସଲ ଏବଂ ପଶୁସମ୍ପଦ",
            "organic" to "ଜୈବିକ",
            "transitional" to "ପରିବର୍ତ୍ତନଶୀଳ",
            "conventional" to "ପାରମ୍ପରିକ",
            "pending" to "ବାକି ଅଛି",
            "conduct_inspection" to "ଯାଞ୍ଚ ଆରମ୍ଭ କରନ୍ତୁ",
            "audit_target_farmer" to "ଲକ୍ଷ୍ୟ କୃଷକଙ୍କ ଯାଞ୍ଚ",
            "select_audit_result" to "ଯାଞ୍ଚ ସିଦ୍ଧାନ୍ତ ବାଛନ୍ତୁ *",
            "submit_compliance_report" to "ଅନୁପାଳନ ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ",
            "auditor_name" to "ଯାଞ୍ଚକାରୀଙ୍କ ନାମ",
            "audit_date" to "ଯାଞ୍ଚ ତାରିଖ",
            "critical_compliance_notice" to "ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ଅନୁପାଳନ ସୂଚନା",
            "fail_notice_text" to "ଫେଲ୍ (FAIL) ଘୋଷଣା କଲେ ପ୍ରମାଣପତ୍ର ସ୍ଥିତି ସ୍ଥଗିତ ହେବ। ଆପଣଙ୍କୁ ନିମ୍ନରେ ଫସଲ/କୀଟନାଶକ ଅନୁପାଳନ ହୋଇନଥିବା ନିରୀକ୍ଷଣ କିମ୍ବା ଜୈବିକ ନିୟମର ଉଲ୍ଲଂଘନ ସମ୍ପର୍କରେ ସମ୍ପୂର୍ଣ୍ଣ ବିବରଣୀ ପ୍ରଦାନ କରିବାକୁ ହେବ।",
            "obs_notes_fail" to "ନିୟମ ଭଙ୍ଗ ନିରୀକ୍ଷଣ (ଆବଶ୍ୟକ) *",
            "obs_notes_optional" to "ଯାଞ୍ଚ ନିରୀକ୍ଷଣ / ଯାଞ୍ଚ ଲଗ୍ (ବୈକଳ୍ପିକ)",
            "full_complies" to "ସମ୍ପୂର୍ଣ୍ଣ ଅନୁପାଳନ କରେ",
            "red_flags" to "ବିପଦ ସଙ୍କେତ / ସତର୍କତା",
            "need_verification" to "ଯାଞ୍ଚ ଆବଶ୍ୟକ",
            "registration_id" to "ପଞ୍ଜୀକରଣ ID",
            "crops_farming_practices" to "ଫସଲ ଏବଂ ଚାଷ ପ୍ରଣାଳୀ",
            "livestock_asset_details" to "ପଶୁସମ୍ପଦ ଏବଂ ପ୍ରାଣୀ ବିବରଣୀ",
            "ics_group_compliance_record" to "ଆଭ୍ୟନ୍ତରୀଣ ନିୟନ୍ତ୍ରଣ ବ୍ୟବସ୍ଥା ଗ୍ରୁପ୍ ଏବଂ ଅନୁପାଳନ ରେକର୍ଡ",
            "certification_file" to "ପ୍ରମାଣପତ୍ର ଫାଇଲ୍",
            "ics_group_name" to "ଆଇସିଏସ ଗ୍ରୁପ୍ ନାମ",
            "reg_mapped_date" to "ପଞ୍ଜୀକରଣ ମ୍ୟାପିଂ ତାରିଖ",
            "last_active_inspection" to "ଶେଷ ସକ୍ରିୟ ଯାଞ୍ଚ",
            "inspection_result_status" to "ଯାଞ୍ଚ ସିଦ୍ଧାନ୍ତ ସ୍ଥିତି",
            "next_scheduled_audit" to "ଆଗାମୀ ନିର୍ଦ୍ଧାରିତ ଯାଞ୍ଚ",
            "red_flags_log" to "ନିୟମ ଭଙ୍ଗ ବିପଦ ସଙ୍କେତ ଲଗ୍:",
            "unscheduled" to "ଅନିର୍ଦ୍ଧାରିତ",
            "never_inspected" to "କେବେ ଯାଞ୍ଚ ହୋଇନାହିଁ",
            "pending_inspection" to "ଯାଞ୍ଚ ବାକି ଅଛି",
            "primary_profile_identity" to "ପ୍ରାଥମିକ ପ୍ରୋଫାଇଲ୍ ଏବଂ ପରିଚୟ",
            "village_location" to "ଗ୍ରାମର ସ୍ଥିତି",
            "gram_panchayat" to "ଗ୍ରାମ ପଞ୍ଚାୟତ",
            "taluka" to "ତହସିଲ",
            "district" to "ଜିଲ୍ଲା",
            "state" to "ରାଜ୍ୟ",
            "geographic_gps" to "ଭୌଗୋଳିକ ଜିପିଏସ",
            "primary_crops_mapped" to "ମ୍ୟାପିଂ ହୋଇଥିବା ପ୍ରାଥମିକ ଫସଲ",
            "intercrops_secondary" to "ଅନ୍ତଃଫସଲ / ଦ୍ୱିତୀୟକ ଫସଲ",
            "seeds_sourcing" to "ବିହନ ସଂଗ୍ରହ",
            "previous_yield" to "ପୂର୍ବ ଉତ୍ପାଦନ",
            "is_chem_pesticides_used" to "ରାସାୟନିକ କୀଟନାଶକ ବ୍ୟବହୃତ ହୋଇଛି କି?",
            "is_chem_fertilizers_used" to "ରାସାୟନିକ ସାର ବ୍ୟବହୃତ ହୋଛି କି?",
            "pesticide_log" to "କୀଟନାଶକ ଲଗ୍",
            "fertilizer_log" to "ସାର ଲଗ୍",
            "no_yield_logs" to "କୌଣସି ଉତ୍ପାଦନ ଲଗ୍ ନାହିଁ",
            "none_listed" to "କିଛି ତାଲିକାଭୁକ୍ତ ହୋଇନାହିଁ",
            "un_saved_warning" to "ଏହି ବିବରଣୀରେ ସଂରକ୍ଷିତ ହୋଇନଥିବା ସ୍ଥାନୀୟ ସଂଶୋଧନ ଅଛି। ଅନଲାଇନ୍ ହେଲେ ଏହା ଆପେଆପେ ସିଙ୍କ୍ ହେବ, କିମ୍ବା ଆପ୍ ସେଟିଙ୍ଗ୍ସରେ ମାନୁଆଲି ସିଙ୍କ୍ କରାଯାଇପାରିବ।",
            "previous" to "ପୂର୍ବବର୍ତ୍ତୀ",
            "next_sec" to "ପରବର୍ତ୍ତୀ ବିଭାଗ",
            "complete_sync" to "ସମ୍ପୂର୍ଣ୍ଣ ଏବଂ ସିଙ୍କ୍",
            "edit_farmer_rec" to "କୃଷକ ରେକର୍ଡ ସଂଶୋଧନ",
            "new_farmer_reg" to "ନୂତନ କୃଷକ ପଞ୍ଜୀକରଣ",
            "log_farm_inspection" to "ଫାର୍ମ ଯାଞ୍ଚ ଲଗ୍"
        )
    )

    fun getString(language: AppLanguage, key: String): String {
        return translations[language]?.get(key) ?: translations[AppLanguage.ENGLISH]?.get(key) ?: key
    }
}
